import type { Metadata } from 'next'
import { routing } from '@/i18n/routing'
import { Inter } from 'next/font/google'
import './globals.css'
import { InstallProviders } from '@/provider/install-providers'
import { getMessages, setRequestLocale } from 'next-intl/server'
import { Header, SideBar } from '@/components'

const inter = Inter({ subsets: ['latin'] })

type Props = {
  children: React.ReactNode
  params: { locale: string }
}

export function generateStaticParams() {
  return routing.locales.map((locale: string) => ({ locale }))
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function GlobalLayout({ children, params: { locale } }: Props) {
  setRequestLocale(locale)
  const messages = await getMessages()
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <InstallProviders locale={locale} messages={messages}>
          <main className="relative h-screen overflow-hidden bg-gray-100 dark:bg-gray-800">
            <div className="flex items-start justify-between">
              <SideBar />
              <div className="flex flex-col w-full md:space-y-4">
                <Header />
                {children}
              </div>
            </div>
          </main>
        </InstallProviders>
      </body>
    </html>
  )
}
