import type { Metadata } from 'next'
import { Header, SideBar } from '@/components/index'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function AppLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <main className="relative h-screen overflow-hidden bg-gray-100 dark:bg-gray-800">
      <div className="flex items-start justify-between">
        <SideBar />
        <div className="flex flex-col w-full md:space-y-4">
          <Header />
          {children}
        </div>
      </div>
    </main>
  )
}
